### PR TITLE
Smallchanges

### PR DESCRIPTION
**Pull request by SimonMcN**
Just some suggestions

### CODE REVIEW

**Comment by diegogslomp** [comment]
Hello!

Since I'm using the docker compose plugin instead docker-compose script, the command for that doesn't have the '-' in the middle, more details at https://docs.docker.com/compose/compose-v2/. 

About the quotes around the boolean value, my vscode linter doesn't change/fix that, did you have problems with no quoted boolean in dockerfiles?

I'm closing this pull, fell free to reopen and thanks for your feedback!

**Comment by SimonMcN** [comment]
It's your call.  I was just trying to help.  I've been using docker for a few years, and docker-compose, as far as I am aware, is in more common use than the plugin.  Maybe the doc could be updated to reference both tools ?  docker-compose would not start without the quotes around the false statement.

**Comment by SimonMcN** [comment]
I also had this issue inside my virtualised machine that I tried to compile it on

https://github.com/ansible/awx/issues/11879

**Comment by SimonMcN** [comment]
Linux 5.15.0-52 Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:01:58 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 17:59:49 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.10.6
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022

**Pull request closed without merging**
